//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace provider.faculdade.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int IdDisciplina { get; set; }
        public int IdSemestre { get; set; }
        public int IdTurma { get; set; }
        public int Matricula { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Disciplina Disciplina { get; set; }
        public virtual Semestre Semestre { get; set; }
        public virtual Turma Turma { get; set; }
    }
}
